let albums = [
  {
    name: "Almendra",
    artist: "Almedra",
    releaseDate: 1970,
    genre: ["Pop", "Psychedelic", "Rock"],
    albumLength: 68,
    albumAmount: 20,
    cover: "Almendra.png",
  },
  {
    name: "An Innocent Man",
    artist: "Billy Joel",
    releaseDate: 1983,
    genre: ["Pop", "Rock"],
    albumLength: 41,
    albumAmount: 10,
    cover: "AnInnocentMan.png",
  },
  {
    name: "The Beatles (The White Album)",
    artist: "The Beatles",
    releaseDate: 1968,
    genre: ["Pop", "Rock"],
    albumLength: 99,
    albumAmount: 31,
    cover: "TheBeatlesTheWhiteAlbum.png",
  },
  {
    name: "I LAY DOWN MY LIFE FOR YOU",
    artist: "JPEGMAFIA",
    releaseDate: 2024,
    genre: ["Experimental", "Hardcore", "Hip-Hop"],
    albumLength: 41,
    albumAmount: 14,
    cover: "ILayMyLifeDownForYou.png",
  },
  {
    name: "The Bridge",
    artist: "Billy Joel",
    releaseDate: 1986,
    genre: ["Piano", "Pop", "Rock"],
    albumLength: 41,
    albumAmount: 9,
    cover: "TheBridge.png",
  },
  {
    name: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    releaseDate: 1973,
    genre: ["Piano", "Pop", "Rock"],
    albumLength: 76,
    albumAmount: 17,
    cover: "GoodbyeYellowBrickRoad.png",
  },
  {
    name: "Loaded (Remastered)",
    artist: "The Velvet Underground",
    releaseDate: 1970,
    genre: ["Pop", "Rock"],
    albumLength: 56,
    albumAmount: 14,
    cover: "LoadedRemastered.png",
  },
  {
    name: "Weezer (Deluxe Edition)",
    artist: "Weezer",
    releaseDate: 2004,
    genre: ["Alternative", "Pop", "Power", "Rock"],
    albumLength: 92,
    albumAmount: 24,
    cover: "WeezerDeluxeEdition.png",
  },
  {
    name: "Candy Coated Fury",
    artist: "Reel Big Fish",
    releaseDate: 2012,
    genre: ["Punk", "Ska"],
    albumLength: 55,
    albumAmount: 14,
    cover: "CandyCoatedFury.png",
  },
  {
    name: "The Velvet Undergorund & Nico (45th Anniversary Edition)",
    artist: "The Velvet Underground",
    releaseDate: 1967,
    genre: ["Art", "Experimental", "Rock"],
    albumLength: 49,
    albumAmount: 11,
    cover: "TheVelvetUnderground&Nico45thAnniversaryEdition.png",
  },
  {
    name: "Fetty Wap (Deluxe Edition)",
    artist: "Fetty Wap",
    releaseDate: 2015,
    genre: ["East-Coast", "Hip-Hop", "Pop", "Rap", "Trap"],
    albumLength: 77,
    albumAmount: 20,
    cover: "FettyWapDeluxeEdition.png",
  },
  {
    name: "Yoshimi Battles the Pink Robots",
    artist: "The Flaming Lips",
    releaseDate: 2002,
    genre: ["Neo-Psychedelia", "Pop", "Psychedelic"],
    albumLength: 48,
    albumAmount: 11,
    cover: "YoshimiBattlesThePinkRobots.png",
  },
  {
    name: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars (2012 Remaster)",
    artist: "David Bowie",
    releaseDate: 1972,
    genre: ["Glam", "Pop", "Rock"],
    albumLength: 39,
    albumAmount: 11,
    cover: "TheRiseAndFallOfZiggyStardustAndTheSpidersFromMars2012Remaster.png",
  },
  {
    name: "Pinkerton",
    artist: "Weezer",
    releaseDate: 1996,
    genre: ["Alternative", "Pop", "Power", "Rock"],
    albumLength: 35,
    albumAmount: 10,
    cover: "Pinkerton.png",
  },
  {
    name: "Lahai",
    artist: "Sampha",
    releaseDate: 2023,
    genre: ["Alternative", "R&B"],
    albumLength: 41,
    albumAmount: 14,
    cover: "Lahai.png",
  },
  {
    name: "Disintegration",
    artist: "The Cure",
    releaseDate: 1989,
    genre: ["Gothic", "Post-Punk", "Rock"],
    albumLength: 72,
    albumAmount: 12,
    cover: "Disintegration.png",
  },
  {
    name: "OK Computer",
    artist: "Radiohead",
    releaseDate: 1997,
    genre: ["Alternative", "Art", "Rock"],
    albumLength: 54,
    albumAmount: 12,
    cover: "OkComputer.png",
  },
  {
    name: "What's Going On",
    artist: "Marvin Gaye",
    releaseDate: 1971,
    genre: ["Progressive", "Soul"],
    albumLength: 36,
    albumAmount: 9,
    cover: "WhatsGoingOn.png",
  },
  {
    name: "NO HANDS",
    artist: "Joey Valence & Brae",
    releaseDate: 2024,
    genre: ["East-Coast", "Hardcore", "Hip-Hop"],
    albumLength: 31,
    albumAmount: 12,
    cover: "NoHands.png",
  },
  {
    name: "CHROMAKOPIA",
    artist: "Tyler, The Creator",
    releaseDate: 2024,
    genre: ["Hip-Hop", "Neo-Soul", "West-Coast"],
    albumLength: 53,
    albumAmount: 14,
    cover: "Chromakopia.png",
  },
  {
    name: "Hysteria",
    artist: "Def Leppard",
    releaseDate: 1987,
    genre: ["Glam", "Hardcore", "Metal", "Rock"],
    albumLength: 63,
    albumAmount: 12,
    cover: "Hysteria.png",
  },
  {
    name: "The Nylon Curtain",
    artist: "Billy Joel",
    releaseDate: 1982,
    genre: ["Piano", "Pop", "Rock"],
    albumLength: 42,
    albumAmount: 9,
    cover: "TheNylonCurtain.png",
  },
  {
    name: "Midnight Marauders",
    artist: "A Tribe Called Quest",
    releaseDate: 1993,
    genre: ["Boom-Bap", "East-Coast", "Hip-Hop", "Jazz-Rap"],
    albumLength: 42,
    albumAmount: 9,
    cover: "TheNylonCurtain.png",
  },
];
export { albums };
