let albums = [
  {
    name: "Almendra",
    artist: "Almedra",
    releaseDate: 1970,
    genre: "Rock y Alternativo",
    albumLength: 68,
    albumAmount: 20,
  },
  {
    name: "An Innocent Man",
    artist: "Billy Joel",
    releaseDate: 1983,
    genre: "Rock",
    albumLength: 41,
    albumAmount: 10,
  },
  {
    name: "The Beatles (The White Album)",
    artist: "The Beatles",
    releaseDate: 1968,
    genre: "Rock",
    albumLength: 99,
    albumAmount: 31,
  },
  {
    name: "I LAY DOWN MY LIFE FOR YOU",
    artist: "JPEGMAFIA",
    releaseDate: 2024,
    genre: "Hip-Hop",
    albumLength: 41,
    albumAmount: 14,
  },
  {
    name: "The Bridge",
    artist: "Billy Joel",
    releaseDate: 1986,
    genre: "Pop",
    albumLength: 41,
    albumAmount: 9,
  },
  {
    name: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    releaseDate: 1973,
    genre: "Rock",
    albumLength: 76,
    albumAmount: 17,
  },
  {
    name: "Loaded (Remastered)",
    artist: "The Velvet Underground",
    releaseDate: 1970,
    genre: "Rock",
    albumLength: 56,
    albumAmount: 14,
  },
  {
    name: "Weezer (Deluxe Edition)",
    artist: "Weezer",
    releaseDate: 2004,
    genre: "Rock",
    albumLength: 92,
    albumAmount: 24,
  },
  {
    name: "Candy Coated Fury",
    artist: "Reel Big Fish",
    releaseDate: 2012,
    genre: "Punk",
    albumLength: 55,
    albumAmount: 14,
  },
  {
    name: "The Velvet Undergorund & Nico (45th Anniversary Edition)",
    artist: "The Velvet Underground",
    releaseDate: 1967,
    genre: "Rock",
    albumLength: 49,
    albumAmount: 11,
  },
  {
    name: "Fetty Wap (Deluxe Edition)",
    artist: "Fettyy Wap",
    releaseDate: 2015,
    genre: "Hip-Hop",
    albumLength: 77,
    albumAmount: 20,
  },
  {
    name: "Yoshimi Battles the Pink Robots",
    artist: "The Flaming Lips",
    releaseDate: 2002,
    genre: "Alternative",
    albumLength: 48,
    albumAmount: 11,
  },
  {
    name: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars (2012 Remaster)",
    artist: "David Bowie",
    releaseDate: 1972,
    genre: "Pop",
    albumLength: 39,
    albumAmount: 11,
  },
  {
    name: "Pinkerton",
    artist: "Weezer",
    releaseDate: 1996,
    genre: "Rock",
    albumLength: 35,
    albumAmount: 10,
  },
  {
    name: "Lahai",
    artist: "Sampha",
    releaseDate: 2023,
    genre: "Electronic",
    albumLength: 41,
    albumAmount: 14,
  },
  {
    name: "Disintegration",
    artist: "The Cure",
    releaseDate: 1989,
    genre: "Alternative",
    albumLength: 72,
    albumAmount: 12,
  },
  {
    name: "OK Computer",
    artist: "Radiohead",
    releaseDate: 1997,
    genre: "Alternative",
    albumLength: 54,
    albumAmount: 12,
  },
  {
    name: "What's Going On",
    artist: "Marvin Gaye",
    releaseDate: 1971,
    genre: "R&B",
    albumLength: 36,
    albumAmount: 9,
  },
  {
    name: "NO HANDS",
    artist: "Joey Valence & Brae",
    releaseDate: 2024,
    genre: "Alternative",
    albumLength: 31,
    albumAmount: 12,
  },
  {
    name: "CHROMAKOPIA",
    artist: "Tyler, The Creator",
    releaseDate: 2024,
    genre: "Hip-Hop",
    albumLength: 53,
    albumAmount: 14,
  },
];
export { albums };
